stages:
    - test

test-pr:
    tags: 
        - ui_test
    when: always
    stage: test
    before_script:
        - pip install -e git+https://${AUTH_USER}:${REPO_ACCESS_TOKEN}@git@git.labs.nuance.com:akanchha.agupta/test-pr-proj.git#egg=test-subtree-proj
    script:
        - python test_me.py
        
bridge-job:
    stage: test
    script:
    - "curl --request POST --form token=41d3d3a0b0b0aacd5653f81815528e --form ref=master https://gitlab.example.com/api/v4/projects/15966/trigger/pipeline"
    
