stages:
    - test
    - trigger_api

test-pr:
    tags: 
        - li-run
    when: always
    stage: test
    before_script:
        #- pip install -e git+https://${AUTH_USER}:${REPO_ACCESS_TOKEN}@git@git.labs.nuance.com:akanchha.agupta/test-pr-proj.git#egg=test-subtree-proj
    script:
        #- python test_me.py
        echo "Running tests"
        
bridge-job:
    stage: trigger_api
    tags:
        - li-run
    script:
    # - "curl --request POST --form token=41d3d3a0b0b0aacd5653f81815528e --form ref=master https://git.labs.nuance.com/api/v4/projects/15966/trigger/pipeline"
      - "curl --request POST --form token=${CI_JOB_TOKEN} --form ref=master https://git.labs.nuance.com/api/v4/projects/15966/trigger/pipeline"
    
